config:
  ignore:
    paths:
      - /api/public/index.php
techstack:
  application:
    - laravel:9.52.15
    - php:8.0.2
    - typescript
    - nuxt:3.5.1
    - nginx:1.21.6
    - sass:1.55.0
    - redis:7.0.4
    - beanstalkd
    - prettier:2.8.8
  database:
    - postgresql
    - linode
  devops:
    - kubernetes
    - fluxcd
    - docker
    - git
    - vscode
    - helm
  business_tools:
    - slack
    - figma
  utilities:
    - elasticsearch:8.11.1
    - metabase
