language: java

jdk:
  - openjdk11

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

script:
  # Build your application (e.g., compile code, run tests, etc.)
  - ./gradlew clean build

deploy:
  provider: script
  script: 
    # Deploy your application using Helm
    # Make sure you have Helm installed and configured properly
    - helm upgrade --install myapp ./path/to/helm/chart --namespace mynamespace
  on:
    branch: main

after_success:
  # Perform any post-deployment actions or notifications
  - echo "Deployment successful. Sending notifications..."

after_failure:
  # Handle failure scenarios (e.g., rollback, send notifications, etc.)
  - echo "Deployment failed. Taking necessary actions..."
