on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string
      unique_tag_suffix:
        required: true
        type: string
      app_url:
        required: true
        type: string

env:
  HARBOR_REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

jobs:
  build:
    runs-on: arc-runners-sun
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.app_url }}
    env:
      TAG: ${{ inputs.tag }}
      APP_URL: ${{ inputs.app_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to ${{ inputs.environment }}
        run: |
          export UNIQUE_TAG="run-$GITHUB_RUN_NUMBER${{ inputs.unique_tag_suffix }}"
          echo "$HARBOR_PASSWORD" | docker login $HARBOR_REGISTRY -u "$HARBOR_USERNAME" --password-stdin
          make docker-pull
          make docker-build
          make docker-push
